backend:
  name: github
  repo: Joseph-Barat/just-train.github.io   # CHANGE this to your GitHub repo name
  branch: main                  # Or master, if that's your branch

media_folder: "assets/uploads"   # Where uploaded images go
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string", pattern: ["<!-- cms:hero_title -->([\\s\\S]*?)<!-- /cms:hero_title -->", "<!-- cms:hero_title -->{{value}}<!-- /cms:hero_title -->"] }
          - { label: "Hero Paragraph", name: "hero_paragraph", widget: "text", pattern: ["<!-- cms:hero_paragraph -->([\\s\\S]*?)<!-- /cms:hero_paragraph -->", "<!-- cms:hero_paragraph -->{{value}}<!-- /cms:hero_paragraph -->"] }
          - { label: "Hero Subtext", name: "hero_subtext", widget: "string", pattern: ["<!-- cms:hero_subtext -->([\\s\\S]*?)<!-- /cms:hero_subtext -->", "<!-- cms:hero_subtext -->{{value}}<!-- /cms:hero_subtext -->"] }
